language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
before_script:
  - source ./travis_pr_script.sh
script:
  - coverage run --source=bot/ -m pytest -x
after_script:
  - coverage report
